<a href="https://colab.research.google.com/github/yashbhatt0508/cv-learn/blob/main/cv_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
# x=torch.tensor([1,2,3,4])
# print(x)
# print(x.shape)


tensor([1, 2, 3, 4])
torch.Size([4])


In [ ]:
img = torch.tensor([
    [0,10,20],
    [30,40,50],
    [60,70,80]
])
print(img)
print(img.shape)

tensor([[ 0, 10, 20],
        [30, 40, 50],
        [60, 70, 80]])
torch.Size([3, 3])


In [ ]:
img = img.unsqueeze(0)
print(img.shape)

torch.Size([1, 3, 3])


In [ ]:
# unsqueeze is used to add one more dimension

In [ ]:
img = img.unsqueeze(0)
print(img.shape)

torch.Size([1, 1, 3, 3])


In [ ]:
img = torch.randn([1,32,224,224])
print(img)
print(img.shape)

tensor([[[[ 1.1695,  0.4080,  0.9952,  ...,  0.9217,  0.7639, -0.0906],
          [-1.5065, -0.8825, -0.0090,  ...,  0.1993, -1.2169,  1.3287],
          [-1.9179, -0.5041,  1.0582,  ..., -1.1106, -1.3977,  1.0604],
          ...,
          [ 0.7919,  0.0560, -0.2192,  ..., -1.4435, -1.6065, -1.7489],
          [ 0.7954, -0.5649, -0.1948,  ...,  0.0528,  0.8866,  0.3804],
          [-0.3391,  0.3843,  1.8610,  ..., -0.3943,  0.5800,  0.6369]],

         [[ 1.4599, -0.8886,  2.4101,  ..., -0.1846, -0.4668,  0.1335],
          [ 1.1519,  0.5170, -1.5397,  ...,  0.0184,  0.5335, -0.4210],
          [-1.4419,  0.6934,  0.6145,  ...,  0.4757, -0.3238,  0.9456],
          ...,
          [ 1.3143,  1.6479, -1.7011,  ...,  0.1606,  0.0951, -1.6826],
          [-1.8293,  0.8428, -1.6212,  ..., -0.1878,  0.3749,  1.4892],
          [ 0.3573,  0.3355,  0.3729,  ...,  1.4698, -0.5844, -0.7938]],

         [[-1.1035,  1.4670, -0.5805,  ..., -0.6570, -0.1110, -0.3523],
          [-0.3342,  1.9648, -

In [ ]:
print(torch.cuda.is_available())

False


In [ ]:
from torch.utils.data import TensorDataset


x = torch.tensor([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])

y = torch.tensor([0,1,0,1])

data = TensorDataset(x,y)

print(len(data))
print(data[0])

4
(tensor([1, 2]), tensor(0))


In [ ]:
from torch.utils.data import DataLoader

Loader = DataLoader(
    data,
    batch_size=2,
    shuffle=True
)

for x_batch,y_batch in Loader:
  print(f"x_batch is {x_batch}")
  print(f"y_batch is {y_batch}")

x_batch is tensor([[7, 8],
        [5, 6]])
y_batch is tensor([1, 0])
x_batch is tensor([[3, 4],
        [1, 2]])
y_batch is tensor([1, 0])


In [ ]:
# ### Important Terms

# Dataset → collection of individual samples
# DataLoader → creates batches from the Dataset
# Batch → group of samples processed together
# Iteration/Step → one batch processed
# Epoch → entire dataset processed once


# Example:
# Dataset = 1000 images
# Batch size = 100

# Iterations per epoch = 1000 / 100 = 10

In [ ]:
# model building
import torch.nn as nn
class simpleModal(nn.Module):

  def __init__(self):
    super().__init__()

    self.layer = nn.Linear(2,1)

  def forward(self,x):
    return self.layer(x)

model = simpleModal()
print(model)

simpleModal(
  (layer): Linear(in_features=2, out_features=1, bias=True)
)


In [ ]:
print(model.layer.weight)
print(model.layer.bias)

Parameter containing:
tensor([[ 0.5205, -0.2031]], requires_grad=True)
Parameter containing:
tensor([0.5709], requires_grad=True)


In [ ]:
# giving x values into model

x = torch.tensor([5.0,2.0])
output=model(x)

print(output)

tensor([2.7671], grad_fn=<ViewBackward0>)


In [ ]:
model(x)

tensor([2.7671], grad_fn=<ViewBackward0>)