<a href="https://colab.research.google.com/github/yashbhatt0508/cv-learn/blob/main/cv_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
# x=torch.tensor([1,2,3,4])
# print(x)
# print(x.shape)


In [ ]:
img = torch.tensor([
    [0,10,20],
    [30,40,50],
    [60,70,80]
])
print(img)
print(img.shape)

tensor([[ 0, 10, 20],
        [30, 40, 50],
        [60, 70, 80]])
torch.Size([3, 3])


In [ ]:
img = img.unsqueeze(0)
print(img.shape)

torch.Size([1, 3, 3])


In [ ]:
# unsqueeze is used to add one more dimension

In [ ]:
img = img.unsqueeze(0)
print(img.shape)

torch.Size([1, 1, 3, 3])


In [ ]:
img = torch.randn([1,32,224,224])
print(img)
print(img.shape)

tensor([[[[ 8.6664e-01, -7.3980e-01,  1.2026e+00,  ..., -5.6890e-01,
            2.5303e-01, -1.5732e+00],
          [-1.5696e-01,  6.7933e-01,  4.2159e-01,  ...,  6.1898e-01,
            3.7947e-02,  4.9018e-01],
          [ 2.7334e+00,  1.1979e+00, -4.7790e-01,  ...,  8.5034e-01,
            1.0258e+00, -2.5534e+00],
          ...,
          [ 8.7215e-01,  1.1749e+00, -4.8800e-01,  ..., -8.7851e-01,
            4.9074e-01,  2.0651e+00],
          [-4.5851e-01,  1.4087e+00,  3.7795e+00,  ...,  5.9885e-01,
           -3.4658e-02, -1.3324e-01],
          [-3.3590e-01, -6.7468e-01,  9.6446e-01,  ...,  1.1739e+00,
           -2.7815e-01,  1.0836e+00]],

         [[-2.7008e+00, -3.6123e-01, -1.4147e-01,  ..., -3.0706e-01,
           -1.6104e-01,  1.1950e+00],
          [ 1.1473e+00, -2.6384e-01,  2.1245e-01,  ..., -4.4596e-01,
           -2.7457e-01, -4.4505e-01],
          [-1.5555e-02,  1.2238e-03, -9.0369e-01,  ..., -2.5182e-01,
            2.7338e-01, -9.5839e-01],
          ...,
     

In [ ]:
print(torch.cuda.is_available())

False


In [ ]:
from torch.utils.data import TensorDataset


x = torch.tensor([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])

y = torch.tensor([0,1,0,1])

data = TensorDataset(x,y)

print(len(data))
print(data[0])

4
(tensor([1, 2]), tensor(0))


In [ ]:
from torch.utils.data import DataLoader

Loader = DataLoader(
    data,
    batch_size=2,
    shuffle=True
)

for x_batch,y_batch in Loader:
  print(f"x_batch is {x_batch}")
  print(f"y_batch is {y_batch}")

x_batch is tensor([[5, 6],
        [1, 2]])
y_batch is tensor([0, 0])
x_batch is tensor([[3, 4],
        [7, 8]])
y_batch is tensor([1, 1])


In [ ]:
# ### Important Terms

# Dataset → collection of individual samples
# DataLoader → creates batches from the Dataset
# Batch → group of samples processed together
# Iteration/Step → one batch processed
# Epoch → entire dataset processed once


# Example:
# Dataset = 1000 images
# Batch size = 100

# Iterations per epoch = 1000 / 100 = 10

In [ ]:
# model building
import torch.nn as nn
class simpleModal(nn.Module):

  def __init__(self):
    super().__init__()

    self.layer = nn.Linear(2,1)

  def forward(self,x):
    return self.layer(x)

model = simpleModal()
print(model)

simpleModal(
  (layer): Linear(in_features=2, out_features=1, bias=True)
)


In [ ]:
print(model.layer.weight)
print(model.layer.bias)

Parameter containing:
tensor([[-0.0721, -0.5061]], requires_grad=True)
Parameter containing:
tensor([-0.3237], requires_grad=True)


In [ ]:
# giving x values into model

x = torch.tensor([5.0,2.0])
output=model(x)

print(output)

tensor([-1.6963], grad_fn=<ViewBackward0>)


In [ ]:
model(x)

tensor([-1.6963], grad_fn=<ViewBackward0>)

In [ ]:
relu = torch.nn.ReLU()

x = torch.tensor([-1.0,-2.0,0,4.0])
print(relu(x))

tensor([0., 0., 0., 4.])


In [ ]:
import torch
import torch.nn as nn

# Model
model = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4, 1)
)

# Input and target
x = torch.tensor([[5.0, 2.0]])
target = torch.tensor([[4.0]])

# Forward pass
output = model(x)

# Loss
loss_fn = nn.MSELoss()
loss = loss_fn(output, target)

# Backpropagation
loss.backward()

# Gradients
print("Weight gradients:")
print(model[0].weight.grad)

print("\nBias gradients:")
print(model[0].bias.grad)

Weight gradients:
tensor([[-12.8099,  -5.1240],
        [  6.5664,   2.6266],
        [  0.0000,   0.0000],
        [  0.0000,   0.0000]])

Bias gradients:
tensor([-2.5620,  1.3133,  0.0000,  0.0000])


In [ ]:
tar = torch.tensor([4.0])

loss_fn = nn.MSELoss()
loss=loss_fn(output,tar)
print(loss)

tensor(32.4476, grad_fn=<MseLossBackward0>)


None
None
